"""
Django settings for shopora project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n9!(xa6$njr41_^i4i1q^%^&z2r1bi@m-=6%cnx_uote%2p2h*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

def _split_csv_env(name):
    raw_value = (os.getenv(name, "") or "").strip()
    if not raw_value:
        return []
    return [value.strip() for value in raw_value.split(",") if value.strip()]


def _append_unique(values, candidate):
    if candidate and candidate not in values:
        values.append(candidate)


ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".ngrok-free.dev",
    ".ngrok.app",
]
for allowed_host in _split_csv_env("DJANGO_ALLOWED_HOSTS"):
    _append_unique(ALLOWED_HOSTS, allowed_host)

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1",
    "http://localhost",
    "https://*.ngrok-free.dev",
    "https://*.ngrok.app",
]
for trusted_origin in _split_csv_env("DJANGO_CSRF_TRUSTED_ORIGINS"):
    _append_unique(CSRF_TRUSTED_ORIGINS, trusted_origin)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'buyhive.apps.BuyhiveConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shopora.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shopora.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'

# MPESA/Daraja Configuration
MPESA_ENVIRONMENT = 'sandbox'  # 'production' or 'sandbox'
MPESA_CONSUMER_KEY = 'dxD2MGyUL0qLtYLkikrN1Gqko2NPGcU6KGJLGXkk4Vmx9G0C'
MPESA_CONSUMER_SECRET = 'AYl37HUkSu8ssBbWiJh2jVexCAlGeN7bGhm36TBAYxRpPMW69nVLtCF9rej8hGZU'
MPESA_PASSKEY = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_BUSINESS_SHORTCODE = '174379'  # Sandbox shortcode
MPESA_CALLBACK_URL = os.getenv(
    'MPESA_CALLBACK_URL',
    'https://trepidly-unobstinate-alivia.ngrok-free.dev/api/mpesa/callback/',
)

callback_origin = ""
parsed_callback_url = urlparse(MPESA_CALLBACK_URL)
if parsed_callback_url.scheme and parsed_callback_url.netloc:
    callback_origin = f"{parsed_callback_url.scheme}://{parsed_callback_url.netloc}"
    _append_unique(CSRF_TRUSTED_ORIGINS, callback_origin)
    if parsed_callback_url.hostname:
        _append_unique(ALLOWED_HOSTS, parsed_callback_url.hostname)
