# Generated by Django 6.0.3 on 2026-03-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyhive', '0004_order_orderitem_payment_paymentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Default delivery address', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for MPESA payments', max_length=15, null=True),
        ),
    ]
