# Generated by Django 6.0.3 on 2026-03-20 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyhive', '0005_profile_delivery_address_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='bi-basket3', max_length=40)),
                ('description', models.CharField(max_length=180)),
                ('theme', models.CharField(choices=[('citrus', 'Citrus'), ('garden', 'Garden'), ('dairy', 'Dairy'), ('grain', 'Grain'), ('spice', 'Spice'), ('pantry', 'Pantry')], default='pantry', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='buyhive.marketcategory'),
        ),
    ]
